PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX humans: <http://www.inria.fr/2007/09/11/humans.rdfs#>

SELECT ?person ?shoesize WHERE {
  ?person rdf:type humans:Person .
  OPTIONAL { ?person humans:shoesize ?shoesize . }
}
